global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dennis_ananiev'
