version: '3.3'
services:  
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  
  ui:
    image: ${DOCKERHUB_USERNAME}/ui:${BUILD_VERSION}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.BUILD_VERSION

  post:
    image: ${DOCKERHUB_USERNAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.POST_DATABASE_HOST 

  comment:
    image: ${DOCKERHUB_USERNAME}/comment:${BUILD_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
